
namespace: chubaofs

component:
  master: true
  datanode: true
  metanode: true
  client: true
  provisioner: false
  monitor: true

image:
  server: liuchengyu/cfs-server:1.3.0
  client: liuchengyu/cfs-client:1.3.0
  grafana: grafana/grafana:6.4.4
  prometheus: prom/prometheus:v2.13.1
  consul: consul:1.6.1
  pull_policy: "IfNotPresent"

# store data,log and other data 
path:
  data: /var/lib/chubaofs
  log: /var/log/chubaofs
  monitor: /var/lib/chubaofs_prometheus

master:
  replicas: 3
  cluster: my-cluster
  labels:
    node_selector_key: chuabaofs-master
    node_selector_value: enabled
  log_level: info
  retain_logs: 2000
  port: 8080
  prof: 10088
  exporter_port: 9510
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

metanode:
  labels:
    node_selector_key: chuabaofs-metanode
    node_selector_value: enabled
  log_level: info
  total_mem: "2147483648"
  port: 9021
  prof: 9092
  raft_heartbeat: 9093
  raft_replica: 9094
  exporter_port: 9511
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

datanode:
  labels:
    node_selector_key: chuabaofs-datanode
    node_selector_value: enabled
  log_level: info
  port: 6000
  prof: 6001
  raft_heartbeat: 9095
  raft_replica: 9096
  exporter_port: 9512
  disks:
    - device: /dev/sda
      retain_space: "21474836480"
    - device: /dev/sdb
      retain_space: "21474836480"
    - device: /dev/sdc
      retain_space: "21474836480"
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

client:
  replicas: 1
  vol_name: "test"
  owner: "chubaofs"
  log_level: info
  exporter_port: 9513
  prof: 10094
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

storageclass:
  provisioner: chubao.io/chubaofs
  name: chubaofs

consul:
  port: 8500
  replicas: 1 

grafana:
  port: 3000
  replicas: 1
  host: monitor.chubaofs.com
  admin_password: !!string 123456
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

prometheus:
  port: 9090
  replicas: 1
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

