{{- if .Values.component.provisioner }}
{{- $envAll := . }}
{{- $namespace := .Values.namespace }}
---
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cfs-csi-service-account
  namespace: {{ $namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cfs-csi-cluster-role-binding
  namespace: {{ $namespace }}
subjects:
  - kind: ServiceAccount
    name: cfs-csi-service-account
    namespace: {{ $namespace }}
roleRef:
  kind: ClusterRole
  name: cfs-csi-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cfs-csi-cluster-role
  namespace: {{ $namespace }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cfs-csi-role
  namespace: {{ $namespace }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cfs-csi-role-binding
  namespace: {{ $namespace }}
subjects:
  - kind: ServiceAccount
    name: cfs-csi-service-account
    namespace: {{ $namespace }}
roleRef:
  kind: Role
  name: cfs-csi-role
  apiGroup: rbac.authorization.k8s.io
---
{{ end }}
