{{- if .Values.component.monitor }}
{{- $envAll := . }}
{{- $namespace := .Values.namespace }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: {{ $namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
   - host: {{ .Values.grafana.host }}
     http:
       paths:
       - backend:
          serviceName: grafana-service
          servicePort: {{ .Values.grafana.port }}
{{ end }}